/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulario;

import clases.Persona;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguel
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupo = new javax.swing.ButtonGroup();
        lblTituloPrincipal = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblBiografia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBiografia = new javax.swing.JTextArea();
        txtfNombre = new javax.swing.JTextField();
        txtfApellido = new javax.swing.JTextField();
        rbHombre = new javax.swing.JRadioButton();
        rbMujer = new javax.swing.JRadioButton();
        chkEstaCasado = new javax.swing.JCheckBox();
        cmbEdad = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPersonas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(null);

        lblTituloPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloPrincipal.setForeground(new java.awt.Color(0, 0, 255));
        lblTituloPrincipal.setText("Mi primer formulario");
        getContentPane().add(lblTituloPrincipal);
        lblTituloPrincipal.setBounds(239, 16, 165, 25);

        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(72, 62, 44, 16);

        lblApellido.setText("Apellido");
        getContentPane().add(lblApellido);
        lblApellido.setBounds(72, 99, 44, 16);

        lblEdad.setText("Edad");
        getContentPane().add(lblEdad);
        lblEdad.setBounds(72, 139, 40, 16);

        jLabel2.setText("Sexo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(72, 175, 25, 16);

        lblEstado.setText("Estado civil");
        getContentPane().add(lblEstado);
        lblEstado.setBounds(72, 213, 59, 16);

        lblBiografia.setText("Biografia");
        getContentPane().add(lblBiografia);
        lblBiografia.setBounds(72, 249, 47, 16);

        txtBiografia.setBackground(new java.awt.Color(204, 255, 255));
        txtBiografia.setColumns(20);
        txtBiografia.setLineWrap(true);
        txtBiografia.setRows(5);
        jScrollPane1.setViewportView(txtBiografia);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(155, 249, 234, 86);
        getContentPane().add(txtfNombre);
        txtfNombre.setBounds(155, 59, 234, 22);
        getContentPane().add(txtfApellido);
        txtfApellido.setBounds(155, 99, 234, 22);

        btnGrupo.add(rbHombre);
        rbHombre.setText("Hombre");
        getContentPane().add(rbHombre);
        rbHombre.setBounds(155, 173, 67, 20);

        btnGrupo.add(rbMujer);
        rbMujer.setText("Mujer");
        getContentPane().add(rbMujer);
        rbMujer.setBounds(240, 173, 53, 20);

        chkEstaCasado.setText("Casado");
        getContentPane().add(chkEstaCasado);
        chkEstaCasado.setBounds(155, 211, 85, 20);

        cmbEdad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", " " }));
        getContentPane().add(cmbEdad);
        cmbEdad.setBounds(155, 139, 234, 22);

        btnGuardar.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar.setForeground(new java.awt.Color(0, 153, 51));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(160, 340, 72, 22);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(240, 340, 75, 22);

        tblPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Edad", "Sexo", "Estado civil", "Biografia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPersonas);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(70, 370, 550, 150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String nom = txtfNombre.getText();
        String apellido = txtfApellido.getText();
        String sexo = "";
        String biografia = txtBiografia.getText();
        boolean estaCasado = chkEstaCasado.isSelected();
        
        if (nom.equals("")) {
            JOptionPane.showMessageDialog(null, "Digite un nombre.");
            txtfNombre.requestFocus();
            return;
        }
        
        if(apellido.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Digite un apellido.");
            txtfApellido.requestFocus();
            return;
        }
        
        if(rbHombre.isSelected())
        {
            sexo = "hombre";
        }
        else if(rbMujer.isSelected())
        {
            sexo = "mujer";
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Seleccione un sexo.");
            return;
        }
        
        String edadString = cmbEdad.getSelectedItem().toString();
        
        if(edadString.equals(" "))
        {
            JOptionPane.showMessageDialog(null, "Seleccione una edad.");
            return;
        }
        int edad = Integer.parseInt(edadString);
        
        Persona persona =  new Persona(nom,apellido,edad,sexo,estaCasado,biografia);
        persona.guardar();
        
        DefaultTableModel dfModel = (DefaultTableModel) tblPersonas.getModel();
        
        Object[] fila = new Object[]
        {
            persona.getNombre(),
            persona.getApellido(),
            persona.getEdad(),
            persona.getSexo(),
            persona.isEsCasado()? "Si": "No",
            persona.getBiografia()
        };
        
        dfModel.addRow(fila);
        limpiar();
        JOptionPane.showMessageDialog(null, "Registrado guardado con exito...");
    }//GEN-LAST:event_btnGuardarActionPerformed

    public void limpiar()
    {
        txtfNombre.setText("");
        txtfApellido.setText("");
        txtBiografia.setText("");
        rbHombre.setSelected(false);
        rbMujer.setSelected(false);
        chkEstaCasado.setSelected(false);
        cmbEdad.setSelectedIndex(0);
    }
    
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
       limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrupo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JCheckBox chkEstaCasado;
    private javax.swing.JComboBox<String> cmbEdad;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblBiografia;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTituloPrincipal;
    private javax.swing.JRadioButton rbHombre;
    private javax.swing.JRadioButton rbMujer;
    private javax.swing.JTable tblPersonas;
    private javax.swing.JTextArea txtBiografia;
    private javax.swing.JTextField txtfApellido;
    private javax.swing.JTextField txtfNombre;
    // End of variables declaration//GEN-END:variables
}
